### PR TITLE
refund page

### PR DESCRIPTION
**Pull request by bdkent**
- simple refund page (at `/refund`) for people to return stuck funds via the UI
- pull "from" address from set wallet in header if available

NOTE: didn't bother with i18n until getting some feedback

Screenshot from 2021-08-12 23-26-25

### CODE REVIEW

**Comment by anon-real** [comment]
Thanks for your great PRs. Sent you some donations.
Can you please resolve conflicts for this and https://github.com/anon-real/sigma-usd/pull/43?

**Comment by bdkent** [comment]
@anon-real conflicts are resolved!

**Comment by anon-real** [comment]
@bdkent seems like there are conflicts again after merging one of your PRs. Also, you can do the same as https://github.com/anon-real/sigma-usd/pull/48#issuecomment-900973954 for this one.

**Comment by bdkent** [comment]
@anon-real footer link added

**Pull request merged**
