### PR TITLE
Adding FAQ

### PR DESCRIPTION
**Pull request by bdkent**
- adds FAQ page with URL slug to jump to specific question
- only includes English for now

Screenshot from 2021-08-12 22-36-20

### CODE REVIEW

**Comment by anon-real** [comment]
How about also adding a link to this page somewhere on the site?

**Comment by bdkent** [comment]
@anon-real I tweaked the header to add an FAQ link. 

I think having the balance in the header doesn't really work. It's too much. It squishes everything too much even before adding a new link:
Screenshot from 2021-08-15 13-31-21

So I removed the balances:
https://user-images.githubusercontent.com/3629629/129487462-4117bf2d-5762-46bb-8155-896617cf290f.mov

Let me know what you think.

**Comment by anon-real** [comment]
@bdkent you can add the link to the bottom of the page (where there is link to ergoplatform.org and others)

**Comment by bdkent** [comment]
> @bdkent you can add the link to the bottom of the page (where there is link to ergoplatform.org and others)

@anon-real so revert the header changes and instead add the link to the bottom?

**Comment by anon-real** [comment]
> > @bdkent you can add the link to the bottom of the page (where there is link to ergoplatform.org and others)
> 
> @anon-real so revert the header changes and instead add the link to the bottom?

Yes, that seems better. And please do this also for the refund PR.

**Comment by bdkent** [comment]
@anon-real header change reverted and footer link added

**Pull request merged**
