### PR TITLE
ResesrveCoin page i18n on initial load

### PR DESCRIPTION
**Pull request by bdkent**
fixes https://github.com/anon-real/sigma-usd/issues/29

forgot the `useTranslation()` on the top level page!

### CODE REVIEW

**Comment by deadit** [comment]
Thanks!

**Comment by anon-real** [comment]
@bdkent please share your Ergo address to receive some donations )

**Comment by bdkent** [comment]
> @bdkent please share your Ergo address to receive some donations )

Thanks, @anon-real!  donations welcome at `9gpLB4HJiZnFarQSJBeyduSvdsLS8zZCZ8vF6mEaVZJNGNBsQ58`  😄 

I'm so impressed with what you all are doing with SigmaUSD and want to see it succeed, so happy to help in any small way I can.

**Comment by bdkent** [comment]
@anon-real did this get deployed?  I am still seeing the issue on the live site.  The fix in this PR worked locally, but now I am worried it's still broken...

**Pull request merged**
